### ISSUE TITLE
TypeError: newrelic.getLinkingMetadata is not a function

### ISSUE THREAD

**Issue by diselop** [newrelic/newrelic-winston-logenricher-node#24]
I used the code 
`
const newrelic = new NewrelicWinston({
        format: winston.format.combine(
          winston.format.label({ label: 'test' }),
          newrelicFormatter()
        ),
      });
`
And I have problem with node_modules/@newrelic/winston-enricher/lib/createFormatter.js:8
    const metadata = newrelic.getLinkingMetadata(true)

TypeError: newrelic.getLinkingMetadata is not a function

**Comment by nijotz** [comment]
`getLinkingMetadata` was added in a recent version of the Node.js New Relic agent. What version of the agent are you using? I'll go see what exact version added that function.

**Comment by nijotz** [comment]
https://docs.newrelic.com/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-620

**Comment by nijotz** [comment]
Looks like it was added in v6.2.0

**Comment by astormnewrelic** [comment]
@diselop we haven't hear from you in a few months so we're going to close this out.  If you're still seeing `newrelic.getLinkingMetadata is not a function` after upgrade to the latest agent please don't hesitate to let us know.
