### ISSUE TITLE
Logs are not sent (shown) in NewRelic

### ISSUE THREAD

**Issue by kristijorgji** [newrelic/newrelic-winston-logenricher-node#35]
## Description

The logs do not show in newrelic after following exactly the steps documented at
https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/logs-context-nodejs/nodejs-configure-winston

## Steps to Reproduce
logger.js content

```
const winston = require('winston');
const newrelicFormatter = require('@newrelic/winston-enricher');

const logger = winston.createLogger({
    level: process.env.LOG_LEVEL || 'debug',
    format: winston.format.combine(winston.format.splat(), newrelicFormatter(), winston.format.prettyPrint()),
    transports: new winston.transports.Console(),
});
module.exports = logger;
```

index.js content

```
const logger = require('./logger');
logger.info('test test test');

// etc express routes stuff all logging info level
```

relevant versions of packages

```
"dependencies": {
    //... other stuff
    "@newrelic/winston-enricher": "^0.1.1",
    "newrelic": "^6.2.0",
    "winston": "^3.3.3"
  },
```

` node -v v14.9.0`

newrelic.js file

I have also properly configured newrelic.js file in root directory with my app name and licence (and in log output I can see service name set properly to my app name), and can also see transactions in apm, but only the logs are not being sent

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

Should be able to see the logs in newrelic by filtering with entity.name: "myapname"
I see a lot of logs in the console during testing, but nothing is sent/displayed in newrelic.

Is there some KB threshold that needs to reach for the buffer before the logs are sent or is just not working ?

BTW APM works fine I can see the node transactions

## Relevant Logs / Console output

Some of newrelic agent logs:

`
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:18:39.664Z","msg":"custom_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:18:44.665Z","msg":"error_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:18:44.665Z","msg":"analytic_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:18:44.665Z","msg":"custom_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:18:49.670Z","msg":"error_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:18:49.671Z","msg":"analytic_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:18:49.671Z","msg":"custom_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:18:54.401Z","msg":"metric_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:18:54.403Z","msg":"error_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:18:54.404Z","msg":"transaction_sample_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:18:54.670Z","msg":"error_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:18:54.672Z","msg":"analytic_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:18:54.672Z","msg":"custom_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:18:59.671Z","msg":"error_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:18:59.672Z","msg":"analytic_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:18:59.673Z","msg":"custom_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:19:04.675Z","msg":"error_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:19:04.676Z","msg":"analytic_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:19:04.676Z","msg":"custom_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:19:09.680Z","msg":"error_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:19:09.680Z","msg":"analytic_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:19:09.681Z","msg":"custom_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:19:14.683Z","msg":"error_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:19:14.683Z","msg":"analytic_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:19:14.683Z","msg":"custom_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:19:19.689Z","msg":"error_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:19:19.689Z","msg":"analytic_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:19:19.689Z","msg":"custom_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:19:24.693Z","msg":"error_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:19:24.694Z","msg":"analytic_event_data Aggregator data send.","component":"base_aggregator"}
{"v":0,"level":30,"name":"newrelic","hostname":"3ba93193f3e8","pid":29,"time":"2020-09-08T19:19:24.694Z","msg":"custom_event_data Aggregator data send.","component":"base_aggregator"}
`

**Comment by astormnewrelic** [comment]
Hello @kristijorgji  -- thanks for swinging by and for the detailed issue!  Before I get _too_ far into this I wanted to let you (and any other readers) know that [support.newrelic.com](https://support.newrelic.com/) and [discuss.newrelic.com/](https://discuss.newrelic.com/) are often much better places to go for this sort of "why doesn't it work" support.  The folks watching those queues are often better equipped to respond in a timely fashion with the right information.  

That said -- I think this might be an (easy to make) expectation mismatch.  From this project's README.md

> The winston-enricher log format adds additional app, distributed trace and span information output as JSON-formatted log messages. This is most commonly used with the New Relic Logs product

That is -- this package will enhance your winston provided logs, but **it does not send those logs to New Relic**.  In order to send logs to New Relic, you need to (at the time of this writing) use either the infrastructure agent, a log forwarding plugin like FluentD, or our Logs API. If you need information on setting up logs, you can find it [on our docs site](https://www.youtube.com/watch?v=EAdGhMRBbzY).

I'm going to close this one out for now, but if we've missed the point of your question/issue don't hesitate to keep the conversation going.

**Comment by kristijorgji** [comment]
> Hello @kristijorgji -- thanks for swinging by and for the detailed issue! Before I get _too_ far into this I wanted to let you (and any other readers) know that [support.newrelic.com](https://support.newrelic.com/) and [discuss.newrelic.com/](https://discuss.newrelic.com/) are often much better places to go for this sort of "why doesn't it work" support. The folks watching those queues are often better equipped to respond in a timely fashion with the right information.
> 
> That said -- I think this might be an (easy to make) expectation mismatch. From this project's README.md
> 
> > The winston-enricher log format adds additional app, distributed trace and span information output as JSON-formatted log messages. This is most commonly used with the New Relic Logs product
> 
> That is -- this package will enhance your winston provided logs, but **it does not send those logs to New Relic**. In order to send logs to New Relic, you need to (at the time of this writing) use either the infrastructure agent, a log forwarding plugin like FluentD, or our Logs API. If you need information on setting up logs, you can find it [on our docs site](https://www.youtube.com/watch?v=EAdGhMRBbzY).
> 
> I'm going to close this one out for now, but if we've missed the point of your question/issue don't hesitate to keep the conversation going.

You got the right point of the conversation. That is correct I expected to see the logs in NewRelic because that is what this documentation said https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/logs-context-nodejs/nodejs-configure-winston

that after installing this enricher should check in LOGS UI and see the logs, so I assumed somehow was more then "enricher" and also sending via the installed Node Agent or API the logs, but thanks for info now is clear is not doing it.

I will search then how to send these logs in a performant way to newrelic, aggregate them somehow instead of making API call for each of them etc

Thank you

**Comment by astormnewrelic** [comment]
Got it @kristijorgji  -- I'll pass on that feedback to our docs teams and see what they can do about making the relationship between `newrelic-winston-logenricher-node` and the main logging product clearer.  Apologies for the confusion.

**Comment by StingyJack** [comment]
As an update we were able to get the logs to write to NR. What is not spelled out anywhere is that the log collection and forwarding is not automatic, with the misleading document pointed out here reinforcing the idea that it was automatic. My program is using a newrelic package, the infra agent is on the machine, this should just work, right?

No. The program dumps the logs to a file (or stdout, etc) and the infra agent reads those as its sources. Collection for forwarding is disconnected from the log writing.  The solution engineer we spoke to (who was great btw) sorted out the misunderstanding in less than 5 minutes and said he would try to get the docs updated.
