### ISSUE TITLE
Support for pinojs?

### ISSUE THREAD

**Issue by JaneJeon** [newrelic/newrelic-winston-logenricher-node#47]
Hi, I know that this isn’t exactly a feature request for this specific library, but I’ve been reading through the source code, and it seems like bulk of the logic is just this: https://github.com/newrelic/newrelic-winston-logenricher-node/blob/main/lib/createFormatter.js#L42

Therefore, would it not be possible to port over this logic to pinojs as well? Pino has gotten to the point where the library provides multiple hooks and transformers *without* the need for an external transport (i.e. no piping), and it’s the other major logging library most people use in production, not to mention Elastic has already added support for pino themselves.

Thanks!

**Comment by carlo-808** [comment]
Thank you for the feature request @JaneJeon and for the feedback into how much work would be involved to add pinojs logging! I will add this as a feature request for prioritization with our product manager.

**Comment by alkiskal** [comment]
I'm also interested in this. Basically anyone that is using fastify and doesn't want to change the default logger (pino) and wants to use newrelic has the same roadblock.

**Comment by bizob2828** [comment]
We released a beta version of this log enricher: `@newrelic/pino-enricher`

  * [GitHub repo](https://github.com/newrelic/newrelic-node-log-extensions/tree/main/packages/pino-log-enricher)
  * [Npm package](https://www.npmjs.com/package/@newrelic/pino-enricher)

Please try it out and give us feedback.  Also, PRs are welcome
