### ISSUE TITLE
Add a test (integration or versioned) that exercises via TypeScript

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/newrelic-winston-logenricher-node#62]
While less likely to break again in the future, current TypeScript type testing is limited to asserting things are set as expected. That doesn't mean that actually work imported into a TypeScript project.

We should have some tests that are actually built in TypeScript to verify everything is compatible.

**Comment by bizob2828** [comment]
migrated to new repo: https://github.com/newrelic/newrelic-node-log-extensions/issues/4
